cache: false
language: python
services:
- docker
os: linux
dist: bionic
env:
  global:
  - BUILD_DIR=builds
  - DOCKERHUB_REPOSITORY=pyomo/linux-test-images
  - secure: NjHTIf7CqadFLAHWq2n5bjB+7qHpUVn9gD9rFDRQNGtBgdeIfry/CZmuUo7W/iXpTiazzsovFbO4xa1B1r2DQsEtSoilRU4VxeUwlO8pa38WkpGe5HwHWjFQ9nsn3WfrMPaaDZUNyuByMYaEOE58BnS5nMfzP4zcZEfu7GUHMQ7lzwlQVYu0djCDQpBkx9a0tCgVSpdTCNAnLSt0u0BU6Uw8PZqlqw+xEEsJckji6ABCLs1N0ib0kYJIteKj2pa5FdyPR8JkzFMONKtV+6piohXDoy83whtquxOJko2oopIMd9kSHyfd/OkJ6kGbJHXWCYT/frqwd9vQaeYQaeE+lAHIQS8jiDlR5yOoV78mtAAkb24sA9bPtgeKDL36wGxgMz+zw8lJynkPZ2jpfNnEgADh/vYuIe5AoEBg6+BnhYXYHnfjw78TmszOe0xv+Y8UlfPwqLiMfizpUqNi4UojXTWnkEk8Re0ommJmMsr0k/PjAzBtp12AU/yP25PuWGkadVqHsw5J8f//Z0EIWtATFEKOWi0kIpj6LeJ97Ra31wwOluu+WBuQNeoYX9unta7ttHkUEw2tJGR3RA7SiiQZQM/lzI8CBIFb4+bVyc72NDX8yfEvJ4v50xWqaS0qW7/7by9oyiynC+ySydHh7ah9ppMqGEylExZVR33/oUickSA=
  - secure: pMfyCBohItRyKYmaqoon4ryYPJPCmWv12iMpbtE1yBcWTadmUaDvZi/zIqwHQjQj+hG+514Uus1BHlWUp7C4ygfwlCSlGWocmmmQhuUxcb5NXIunXpZuDXg7tu8mKBW343ZYDuWt+mrwRFonbdJpyToXv/ffwYgxEJ2h355DMvi8h5IAJeavqoLc/KoYY98XccMGFjgdiGrzWLodOs5mmQjIaetfGjQFtmEWkzOv3q9qgk4ys1EXOccRTAlrDlR8RXGDh+hR6xMyBy2LoRo/Wrhg4geLzXBlYcRb80LxFyHtLIzjnWqkOP8J3RYsa6+o4/ew//G1onkngz0/XJKotzd3IezqSLupDUKBCtroieJJauILZ78zHV0Yauijicd4ciu1/BeBjLg5RDQQWRm7A882yLdcdJ2h7O/YuuXCfc3mSNRSeIfax6fh89ghiRNoZGesu68duJ0nYj7Txbec7SXE3ePh/qUecMJkMhGdQPgKlUC97W0r5G8g80jNygV0Vn//ytjiW79zLSd2tX+12Oy6Xzav6nr/mbbyIv8ssnXHKH4A6bi5C2SQKer9hAZOg2l6PdIgMgkMlAy2LQEAqcFFaBzPXtc5GExseVI5ztm4QinnTFAlkQQ5nSPdEfPu4b5zWYpOyETaexQZOn0OrZatARY7uK3y/G7W6pVLO78=
  matrix:
  - NAME=python_3.8    SRC_IMAGE=python:3.8-buster             SRC_PYTHON_EXE=python
  - NAME=python_3.7    SRC_IMAGE=python:3.7-stretch            SRC_PYTHON_EXE=python
  - NAME=python_3.6    SRC_IMAGE=python:3.6-stretch            SRC_PYTHON_EXE=python
  - NAME=python_3.5    SRC_IMAGE=python:3.5                    SRC_PYTHON_EXE=python
  - NAME=python_2.7    SRC_IMAGE=python:2.7-stretch            SRC_PYTHON_EXE=python
  - NAME=pypy_3        SRC_IMAGE=pypy:3                        SRC_PYTHON_EXE=pypy3
  - NAME=pypy_2        SRC_IMAGE=pypy:2                        SRC_PYTHON_EXE=pypy
  - NAME=anaconda_3    SRC_IMAGE=continuumio/anaconda3:2018.12 SRC_PYTHON_EXE=python
  - NAME=anaconda_2    SRC_IMAGE=continuumio/anaconda:2018.12  SRC_PYTHON_EXE=python

script:
- mkdir ${BUILD_DIR}
- python create_linux_dockerfile.py ${SRC_IMAGE} ${SRC_PYTHON_EXE} ${BUILD_DIR}/${NAME}
- while sleep 9m; do echo "still running..."; done &
- docker build --compress --no-cache -t ${NAME} ${BUILD_DIR}/${NAME}
- docker run ${NAME} /bin/sh -c "sleep 0"
- ID=`docker ps -l -q`
- docker cp ${ID}:/root/dynamic_vars.out .
- docker run ${NAME} rm /root/dynamic_vars.out
- |
  while read p
  do
     docker run ${NAME} /bin/sh -c "sleep 0"
     # get the id of the last container that was run
     ID=`docker ps -l -q`
     docker commit --change "ENV ${p}" ${ID} ${NAME}
  done < dynamic_vars.out

after_success:
  - |
    if test "$TRAVIS_BRANCH" == "master" -a -z "$TRAVIS_PULL_REQUEST_BRANCH"; then
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker tag ${NAME} ${DOCKERHUB_REPOSITORY}:${NAME}
        travis_retry docker push ${DOCKERHUB_REPOSITORY}:${NAME}
    fi
